# services:
#   db:
#     image: postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_PASSWORD: postgres

version: "3.8"
services:
  write-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  read-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASEA="vf-read-db"
  event-store:
    image: mongo:6.0.4
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASEA="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ~ ./scripts/event-store-mongoninit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
